name: Build and Push Image
description: 'Build and push image to ECR'

inputs:
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: 'false'
  tags:
    description: "List of tags"
    required: true
  labels:
    description: "List of metadata for an image"
    required: true
  file:
    description: "Path to the Dockerfile"
    required: true
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  cache-from:
    description: "List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)"
    required: false
  platforms:
    description: "List of target platforms for build"
    required: false
  context:
    description: "Create new Context for builder"
    required: false
    default: 'true'
  target:
    description: "Sets the target stage to build"
    required: false
  role-to-assume:
    description: >-
      Use the provided credentials to assume an IAM role and configure the Actions
      environment with the assumed role credentials rather than with the provided
      credentials
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Context for Buildx
      if: ${{ inputs.context == 'true' }}
      shell: bash
      run: docker context create builders

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        endpoint: builders

    - name: Log in to ECR (ap-northeast-1)
      uses: docker/login-action@v2
      if: ${{ inputs.username != '' && inputs.password != '' }}
      with:
        registry: 836919286826.dkr.ecr.ap-northeast-1.amazonaws.com
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Log in to ECR (ap-southeast-1)
      uses: docker/login-action@v2
      if: ${{ inputs.username != '' && inputs.password != '' }}
      with:
        registry: 836919286826.dkr.ecr.ap-southeast-1.amazonaws.com
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Configure AWS credentials (ap-northeast-1)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-northeast-1

    - name: Log in to ECR (ap-northeast-1)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Configure AWS credentials (ap-southeast-1)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-1

    - name: Log in to ECR (ap-southeast-1)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        labels: ${{ inputs.labels }}
        file: ${{ inputs.file }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: type=inline
        platforms: ${{ inputs.platforms }}
        target: ${{ inputs.target }}
